global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'rabbit_prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'income_service'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:7001']